export const PROJECTS_SYNCHRONIZING = "@projects/PROJECTS_SYNCHRONIZING";
export const PROJECTS_SYNCHRONIZED = "@projects/PROJECTS_SYNCHRONIZED";
export const PROJECTS_SYNCHRONIZATION_ERROR =
  "@projects/PROJECTS_SYNCHRONIZATION_ERROR";
export const UPDATE_PROJECT = "@projects/UPDATE_PROJECT";
